---
# See: https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html#collections-galaxy-meta
namespace: strboul
name: notify
version: 0.1.0
description: Check a command and send a notification on desktop.
readme: README.md
authors:
  - Metin Yazici (https://github.com/strboul/)
license:
  - MIT
license_file: LICENSE
tags:
  - module
  - util
  - notify-send
  - systemd
  - systemd-timer
homepage: https://github.com/strboul/ansible-notify-check
repository: https://github.com/strboul/ansible-notify-check
issues: https://github.com/strboul/ansible-notify-check/issues
